name: circlebox_cloud_flutter
description: CircleBox Cloud companion uploader for Flutter.
version: 0.3.0
publish_to: "none"
homepage: https://github.com/jeremiahseun/circlebox
repository: https://github.com/jeremiahseun/circlebox
issue_tracker: https://github.com/jeremiahseun/circlebox/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  circlebox_flutter:
    path: ../circlebox_flutter
  crypto: ^3.0.3
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0
